[package]
name = "watch-signals"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1.47.1", features = ["macros", "signal", "sync", "rt-multi-thread", "time"] }
